server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DB_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    schemas: public
  main:
    banner-mode: off
  security:
    user:
      name: ${ACTUATOR_USER}
      password: ${ACTUATOR_PASSWORD}
  devtools:
    remote:
      secret: ${SPRING_REMOTE_SECRET}

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
      flywaydb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

com:
  online_store:
    security:
      auth:
        jwt:
          secret: ${JWT_SECRET}
          accessToken: 10080 # 7 day
          refreshToken: 131490 #  3 months
